import discord
import os
import asyncio
import urllib.parse
from groq import AsyncGroq
from flask import Flask
from threading import Thread
from discord.ext import tasks

# --- FLASK KEEP-ALIVE SERVER ---
app = Flask('')

@app.route('/')
def home():
    return "Bot is alive and vibing!"

def run_server():
    port = int(os.environ.get("PORT", 10000))
    app.run(host="0.0.0.0", port=port)

def keep_alive():
    t = Thread(target=run_server)
    t.daemon = True
    t.start()

# --- DISCORD & GROQ SETUP ---
intents = discord.Intents.default()
intents.message_content = True
discord_client = discord.Client(intents=intents)

# You only need these two keys! No image API key needed.
GROQ_KEY = os.getenv("GROQ_API_KEY")
DISCORD_TOKEN = os.getenv("DISCORD_BOT_TOKEN")
ai_client = AsyncGroq(api_key=GROQ_KEY)

# --- THE MEMORY BANK ---
chat_history = {}
MAX_HISTORY = 12 

# --- 20-MINUTE AUTO-ANNOUNCEMENT ---
@tasks.loop(minutes=20)
async def everyone_reminder():
    for channel in discord_client.get_all_channels():
        # Make sure this matches your exact channel name
        if channel.name == "♠️︱chat︱♠️" and isinstance(channel, discord.TextChannel):
            try:
                await channel.send("@everyone wake up! Tag me to chat or ask me to create an image!")
                print("🔥 Sent 20-minute wake-up reminder.")
                break 
            except Exception as e:
                print(f"Failed to send reminder: {e}")

@everyone_reminder.before_loop
async def before_reminder():
    await discord_client.wait_until_ready()
    
@discord_client.event
async def on_ready():
    print(f'🔥 WE LIVE! Logged in as {discord_client.user}')
    if not everyone_reminder.is_running():
        everyone_reminder.start()

# --- MESSAGE HANDLING ---
@discord_client.event
async def on_message(message):
    # Don't let the bot reply to itself
    if message.author == discord_client.user:
        return

    # CRITICAL: Ignore the message unless the bot is specifically tagged
    if not discord_client.user.mentioned_in(message):
        return

    # Clean the bot's tag out of the message text so it only reads your words
    raw_content = message.content.replace(f'<@{discord_client.user.id}>', '').strip()
    
    if not raw_content:
        await message.reply("Yo, what's up? Tag me and say something, or tell me to 'create image'!")
        return

    # ==========================================
    # THE SMART BRAIN ROUTER
    # ==========================================
    # We make your message all lowercase just to check for keywords easily
    # ==========================================
    # THE SMART BRAIN ROUTER (UPGRADED)
    # ==========================================
    # We make your message all lowercase just to check for keywords easily
    check_content = raw_content.lower()
    
    # We set up our flags
    is_image_request = False
    image_prompt = ""

    # Look for image keywords ANYWHERE in the sentence
    if "create image" in check_content:
        is_image_request = True
        # This splits the sentence at the keyword and takes everything after it as the prompt
        image_prompt = raw_content.lower().split("create image")[1].strip()
        
    elif "draw" in check_content:
        is_image_request = True
        image_prompt = raw_content.lower().split("draw")[1].strip()
        
    elif "generate" in check_content:
        is_image_request = True
        image_prompt = raw_content.lower().split("generate")[1].strip()

    # If the user didn't type anything after the trigger word, just use the original message
    if is_image_request and not image_prompt:
        image_prompt = raw_content

    # ==========================================
    # ROUTE A: SEND TO IMAGE API (Free / Unlimited)
    # ==========================================
    if is_image_request:
        if not image_prompt:
            await message.reply("Bro, tell me what to draw! Example: `@bot create image a futuristic city`")
            return
        
        try:
            async with message.channel.typing():
                # We put your text safely into the unlimited free Pollinations URL
                safe_prompt = urllib.parse.quote(image_prompt)
                image_url = f"https://image.pollinations.ai/prompt/{safe_prompt}"
                
                # Make it look clean in a Discord embed
                embed = discord.Embed(title=f"🎨 {image_prompt}", color=discord.Color.purple())
                embed.set_image(url=image_url)
                embed.set_footer(text="Generated by FORB1D🔥 via Pollinations API")
                
                await message.reply(embed=embed)
        except Exception as e:
            print(f"Image API Error: {e}") 
            await message.reply(f"Image generation failed bro: {str(e)}")
        
        # VERY IMPORTANT: We 'return' here so it STOPS and doesn't also talk to Groq
        return

    # ==========================================
    # ROUTE B: SEND TO GROQ API (Text Chat)
    # ==========================================
    user_id = message.author.id

    if user_id not in chat_history:
        chat_history[user_id] = [
            {
                "role": "system", 
                "content": (
                    "You are a chill, highly intelligent bot in the FORBID • OPS Discord server. "
                    "You talk like a real human, keep things conversational, and remember context perfectly. "
                    "You can give detailed answers when asked, but keep the vibe relaxed. "
                    "CRITICAL RULE: If anyone asks who made you, who your owner is, or who created you, "
                    "you must state that you were made by FORB1D🔥. Do not bring this up randomly—only state "
                    "it when specifically asked about your origin, owner, or creator, keeping it natural."
                )
            }
        ]

    # Add your message to Groq's memory
    chat_history[user_id].append({"role": "user", "content": raw_content})

    # Keep memory from getting too big
    if len(chat_history[user_id]) > MAX_HISTORY:
        chat_history[user_id] = [chat_history[user_id][0]] + chat_history[user_id][-(MAX_HISTORY-1):]

    try:
        # Send to Groq
        response = await ai_client.chat.completions.create(
            messages=chat_history[user_id],
            model="llama-3.3-70b-versatile",
        )
        
        bot_reply = response.choices[0].message.content
        chat_history[user_id].append({"role": "assistant", "content": bot_reply})
        
        await message.reply(bot_reply)
        
    except Exception as e:
        print(f"Chat API Error: {e}") 
        chat_history[user_id].pop() 
        await message.reply(f"Bro my brain lagged. Error: `{str(e)}`")

# Start the bot
if __name__ == "__main__":
    keep_alive()
    discord_client.run(DISCORD_TOKEN)
